[defines]
"feature = " = ""

[export]
include = [
    "MaccySync",
    "maccy_sync_*",
]

[fn]
prefix = "maccy_sync_"

[struct]
rename_fields = "SnakeCase"

[enum]
prefix_with_name = true
rename_variants = "SnakeCase"

[language]
cpp = false

[macro_expansion]
bitflags = false
